apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/filebeat-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match this with your PV size
